version: 2

updates:
  - package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "10:30"
    reviewers:
      - "caius"
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
